# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'Reet-Place' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reet-Place
  # Rx
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxGesture'
  pod 'RxDataSources', '~> 5.0'

  # Others
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Then'
  pod 'Kingfisher', '~> 7.0'

  # Map SDK
  pod 'NMapsMap'
  
  # Kakao SDK
  pod 'KakaoSDKCommon', '<= 2.16'
  pod 'KakaoSDKAuth', '<= 2.16'
  pod 'KakaoSDKUser', '<= 2.16'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
	config.build_settings['OTHER_CFLAGS'] = "-Wno-deprecated"
      end
    end
end
