# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(
      type: "appstore",
      app_identifier: "ac.dnd.Reet-Place",
      readonly: true
    )

    increment_build_number(xcodeproj: "Reet-Place.xcodeproj")
    build_app(workspace: "Reet-Place.xcworkspace", scheme: "Reet-Place")
    upload_to_testflight(
      api_key_path: "fastlane/key.json",
      distribute_external: true,
      groups: ["Test by link"],
      changelog: ""
    )
  end
end
